Repository hywax/skillq, pull requests merged in 2024-12, with the labels that each got.

#5 feat: landing page
  .github/workflows/ci.yml
  app/app.config.ts
  app/app.vue
  app/assets/css/main.css
  app/assets/icons/logo-outline.svg
  app/assets/icons/logo.svg
  app/components/app/Activity.vue
  app/components/app/Footer.vue
  app/components/app/Header.vue
  app/components/app/Language.vue
  app/components/app/Logotype.vue
  app/components/app/SponsorButton.vue
  app/components/app/Theme.vue
  app/components/home/Hero.vue
  app/components/home/Icons.vue
  app/layouts/default.vue
  app/pages/builder.vue
  app/pages/index.vue
  i18n/locales/en-US.json
  i18n/locales/hi-IN.json
  i18n/locales/ru-RU.json
  i18n/locales/zh-CN.json
  i18n/vue-i18n.options.ts
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  server/api/activity.get.ts
  server/utils/github.ts
Labels: 0.x

#10 feat: error page
  app/assets/css/main.css
  app/components/app/Header.vue
  app/error.vue
  app/layouts/default.vue
Labels: 0.x

#11 feat: create cli
  .github/workflows/ci.yml
  cli/commands/security.mjs
  cli/index.mjs
  cli/package.json
  cli/utils/icons.mjs
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 0.x

#20 chore: add circle flags
  package.json
  pnpm-lock.yaml
Labels: 0.x

#21 fix: phantom page scroll
  app/assets/css/main.css
Labels: bug, 0.x

#25 chore(deps): update all non-major dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#26 fix: autoimport from `server/utils`
  package.json
  pnpm-lock.yaml
Labels: bug, 0.x

#28 chore(deps): update all non-major dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#29 chore(deps): update all non-major dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#30 chore(deps): update all non-major dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#31 chore(deps): update all non-major dependencies
  cli/package.json
  package.json
  pnpm-lock.yaml
Labels: dependencies
